export const FILE_CODES = {
  z: [
    { code: "za", label: "Overview" },
    { code: "zb", label: "PRD" },
    { code: "zc", label: "Roadmap" },
    { code: "zd", label: "Architecture" },
    { code: "ze", label: "API Docs" },
    { code: "zf", label: "Design System" },
    { code: "zg", label: "User Research" },
    { code: "zh", label: "Requirements" },
    { code: "zi", label: "Testing" },
    { code: "zj", label: "Deployment" },
    { code: "zk", label: "Security" },
    { code: "zl", label: "Performance" },
    { code: "zm", label: "Analytics" },
    { code: "zn", label: "Monitoring" },
    { code: "zo", label: "Backup" },
    { code: "zp", label: "Recovery" },
    { code: "zq", label: "Scaling" },
    { code: "zr", label: "Integration" },
    { code: "zs", label: "Migration" },
    { code: "zt", label: "Training" },
    { code: "zu", label: "Support" },
    { code: "zv", label: "Maintenance" },
    { code: "zw", label: "Compliance" },
    { code: "zx", label: "Persona" },
  ],
  x: [
    { code: "xa", label: "Overview" },
    { code: "xb", label: "PRD" },
    { code: "xc", label: "Business Plan" },
    { code: "xd", label: "Market Research" },
    { code: "xe", label: "Competitive Analysis" },
    { code: "xf", label: "Brand Guidelines" },
    { code: "xg", label: "Marketing Strategy" },
    { code: "xh", label: "Sales Funnel" },
    { code: "xi", label: "Revenue Model" },
    { code: "xj", label: "Financial Projections" },
    { code: "xk", label: "Operations Plan" },
    { code: "xl", label: "Team Structure" },
    { code: "xm", label: "Legal Docs" },
    { code: "xn", label: "Partnerships" },
    { code: "xo", label: "Launch Plan" },
    { code: "xp", label: "Growth Strategy" },
    { code: "xq", label: "Customer Success" },
    { code: "xr", label: "Content Strategy" },
    { code: "xs", label: "Social Media" },
    { code: "xt", label: "PR Strategy" },
    { code: "xu", label: "Metrics & KPIs" },
    { code: "xv", label: "Persona" },
  ],
  y: [
    { code: "ya", label: "Overview" },
    { code: "yb", label: "PRD" },
    { code: "yc", label: "Goals & Vision" },
    { code: "yd", label: "Habits Tracker" },
    { code: "ye", label: "Daily Routine" },
    { code: "yf", label: "Weekly Review" },
    { code: "yg", label: "Monthly Goals" },
    { code: "yh", label: "Quarterly OKRs" },
    { code: "yi", label: "Annual Planning" },
    { code: "yj", label: "Health Metrics" },
    { code: "yk", label: "Fitness Plan" },
    { code: "yl", label: "Nutrition Log" },
    { code: "ym", label: "Sleep Tracking" },
    { code: "yn", label: "Mental Health" },
    { code: "yo", label: "Learning Plan" },
    { code: "yp", label: "Skill Development" },
    { code: "yq", label: "Career Planning" },
    { code: "yr", label: "Financial Goals" },
    { code: "ys", label: "Relationship Map" },
    { code: "yt", label: "Creative Projects" },
    { code: "yu", label: "Travel Plans" },
    { code: "yv", label: "Persona" },
  ],
}
